"""Model-facing interfaces for module E.

The concrete implementation is chosen by a config string
(``AUTUNE_INTELLIGENCE_GAP_CLASSIFIER_IMPL``) and is never referenced directly
outside this package — the same shape modules B, C and D settled on, so the
four can be read the same way.

**No implementation here sends a gap to a third party.** ``Gap.title`` is
generated by module C from utterances module A already masked, but a
cross-meeting classifier is exactly the kind of aggregation
``privacy.md`` section 3 asks this module to be careful with, and there is no
external option to weigh that decision against.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable

PATTERN_TYPES: tuple[str, ...] = (
    "schedule",
    "ownership",
    "budget",
    "stakeholder",
    "risk",
    "scope",
    "other",
)
"""The recurring gap-pattern vocabulary module E classifies into.

C's own ``Gap.category`` (packages/contracts/src/autune_contracts/gap.py) is
free text — the fixture carries ``"technical_spec"`` next to ``"ownership"``
with nothing normalizing between them, because C looks at one meeting at a
time and has no reason to keep a vocabulary stable across meetings (#23, and
module C's own CLAUDE.md: "cross-meeting gap patterns are E's job"). This is
that vocabulary. ``other`` is a real bucket, not an error case — a classifier
forced to pick one of six is a classifier that cannot say "none of these".

Six buckets, chosen as the recurring reasons a meeting leaves something
unresolved: when (schedule), who (ownership), how much (budget), who else
needs to weigh in (stakeholder), what could go wrong (risk), and how big the
work is (scope) — a small, stable taxonomy a classifier can be fit to, rather
than one derived from any single module's sample data.
"""


@dataclass(frozen=True)
class Classification:
    """One gap's pattern type, and how sure the model is of it.

    ``confidence`` is not used to gate anything — there is no candidate/asserted
    split for gap patterns the way ADR 0006 draws one for action items, since
    these are only ever shown aggregated (counts on the dashboard and in the
    weekly report), never as a per-gap assertion a person reacts to. It is
    averaged per pattern type and persisted on ``IntelGapPattern.avg_confidence``
    anyway, for the same reason module B's ``Prediction.confidence`` is: a
    classification that cannot be compared against the next model version
    cannot be recalibrated.
    """

    pattern_type: str
    confidence: float

    def __post_init__(self) -> None:
        if self.pattern_type not in PATTERN_TYPES:
            raise ValueError(f"unknown pattern_type {self.pattern_type!r}; known: {PATTERN_TYPES}")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"confidence out of range: {self.confidence}")


@runtime_checkable
class GapClassifier(Protocol):
    """Recurring pattern type per gap. SetFit few-shot by default.

    Takes a batch rather than one gap at a time: a meeting can raise a dozen
    gaps, and a per-gap call turns one forward pass into a dozen — the same
    reasoning module B's ``Classifier`` and module C's ``EntityExtractor``
    give for their own batches.
    """

    @property
    def model_version(self) -> str:
        """Pinned, and recorded with every ``intel_gap_patterns`` row.

        A pattern distribution that cannot be attributed to a model version
        cannot be compared against the next one, the same argument module C's
        ``EntityExtractor.model_version`` makes for the topic graph.
        """
        ...

    def classify(self, texts: list[str]) -> list[Classification]:
        """One classification per input, in the same order.

        Order is the contract: the caller zips the result against its own gap
        ids rather than the model returning them, so the model never needs to
        know what a gap id is — the same shape as module B's
        ``Classifier.classify``.
        """
        ...
